### ISSUE TITLE
AUR package?

### ISSUE THREAD

**Issue by Sclafus** [abstrakt8/rewind#20]
Thanks for the good work! 
Are you considering to publish this in Arch User Repository? 
It would make the installation process on Arch systems a lot more easy, even if the AppImage is quite nice already

**Comment by abstrakt8** [comment]
Thanks! I need to look into this and then tell you if that is possible

**Comment by Sclafus** [comment]
Here are some pkgbuild from other typescript projects, maybe they can be useful for reference: 
[pnpm](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=pnpm)
[lens](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=lens)
tl;dr the `package()` is a step-by-step compilation. If you add everything you do to compile your application in this function, you should be good to go!
I would do it myself but i'm too unfamiliar with typescript :(

**Comment by aMalteser** [comment]
The [AUR package](https://aur.archlinux.org/packages/rewind-bin) now exists! If you have any issues with the package please leave comments on the AUR page itself.
