### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by sensadarseromodtack** [abstrakt8/rewind#38]
**Describe the solution you'd like**
Is there a way to optimize it in such a way that even low-end or even middle-end laptops can run it smoothly?

**Additional context** (optional)
On the normal or the default settings, the app, when playing a replay runs at a constant 2FPS
![image](https://user-images.githubusercontent.com/93711295/140303400-67e064fd-4667-4d3e-92e3-1d8928d21197.png)

After some setting changes, the highest fps I could get was 22FPS. (the 0-60fps here is because of the break. and we all know that there are no objects in a break therefore my fps wont drop).
![image](https://user-images.githubusercontent.com/93711295/140304603-13ff0601-d4d6-4437-8333-f9d4c38692ad.png)

So, is there a way? or do i just have to suffer and wait until I get a better laptop.

**Comment by abstrakt8** [comment]
Performance optimization is planned, currently certain parts are not optimized at all. It's not that I don't know how to optimize them, but I didn't want to prematurely optimize in order to leave out some features.

**Comment by sensadarseromodtack** [comment]
> Performance optimization is planned, currently certain parts are not optimized at all. It's not that I don't know how to optimize them, but I didn't want to prematurely optimize in order to leave out some features.

Oh okay.. I did not know about that.
Thank you so much!
Hoping for the best!
