### ISSUE TITLE
Error Extracting the File

### ISSUE THREAD

**Issue by CosmicX1000** [abstrakt8/rewind#68]
**Describe the bug**
I just downloaded it and it aborts the installation.
**To Reproduce** (optional)
I used this before i deleted my Visual C++ Redistributable's and it worked
i Think that might be one of the reasons why, i download a Visual C++ and it didn't work.
There's probably an another problem that's causing this.

**Expected behavior**
To use the rewind software as normal

**Screenshots**
![Screenshot_14](https://user-images.githubusercontent.com/93568994/164122980-f9c52b5e-361c-4805-8a0f-582d319d8b9d.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Version [e.g. 7]

**Additional context**

**Please** also provide the following if they are mentioned and related:
* Beatmap
* Replay
* Skin

**Comment by abstrakt8** [comment]
Can you try the new version (0.2.0) and reopen this if this issue persists?
