### ISSUE TITLE
Custom songs folder

### ISSUE THREAD

**Issue by xDololow** [abstrakt8/rewind#76]
**Describe the solution you'd like**
I use custom folder for maps and seems like program cant see them.

**Comment by mzhang0213** [comment]
same, got the ENOENT error in the logs file, the custom songs folder finding procedure seems to be bugged :(:(

**Comment by abstrakt8** [comment]
Which version are you using? Try 0.2.0 and reopen this issue, if it persists.

Related issue: #31
