### ISSUE TITLE
Cant't set a directory

### ISSUE THREAD

**Issue by SimpleOrigiin** [abstrakt8/rewind#83]
I downloaded lastest non beta, and was greeted with thisn 
![image](https://user-images.githubusercontent.com/105546075/202605983-21f7fdbd-457f-4347-9f4a-492966b8ec94.png)
but when i got to osu folder it shows this
![image](https://user-images.githubusercontent.com/105546075/202606084-245b8045-b5f4-4f5f-81b3-a5c121155c35.png)

help pls

**Comment by abstrakt8** [comment]
Hey, it says that the "Replays" folder should also be part of the osu! folder. But this is now not required in the new version 0.2.0.
