### ISSUE TITLE
Add Spinner

### ISSUE THREAD

**Issue by thanhgaming5550** [abstrakt8/rewind#87]
**Ability to see The Spinner**

I want to be able to see the Spinner (how many points did I/Someone in the replay get and RPM (optional)), but Rewind don't show that. So can you add spinner in?

Rewind:
![Rewind Screenshot 2023-01-11T16_50_02 728Z](https://user-images.githubusercontent.com/62001770/211866727-c4b98fc1-6adf-4db8-8d15-005270b70e38.jpg)

osu!:
![screenshot013](https://user-images.githubusercontent.com/62001770/211867163-efec086a-6887-4009-bbfd-3b9fdb324fed.png)

**Comment by abstrakt8** [comment]
Will resolve with #30
