### ISSUE TITLE
broken slider on specific map

### ISSUE THREAD

**Issue by SemKef** [abstrakt8/rewind#90]
**Describe the bug**
beatmap id: 707032 (yaseta - Bluenation [Grace] by Meg), broken slider on 2:32.976. Any replay works.
My replay, just for example: https://drive.google.com/file/d/1xUExlpFidP9XuCumq7BeRl2oW3KoZFKM/view?usp=drivesdk

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 22H2 build 19045.2604

video: https://drive.google.com/file/d/1FZ2e8H8E89ZWV_NVLlP5gUQoQU3DImqm/view?usp=drivesdk
![image](https://user-images.githubusercontent.com/77559101/222608924-a91bf974-b0b9-449e-af4b-dc3f76c6d7d6.png)

**Comment by abstrakt8** [comment]
Interesting, should be fixed in the latest version.

**Comment by abstrakt8** [comment]
Released and fixed
